//! Precise child maps: each aggregate cell has one compiler-written pointer bit.
//! Marking never interprets unmarked Int/Float bits as references.
use super::strings::{HEAP_START, STRIDE};
use wasm_encoder::{BlockType as B, Function, Instruction as I, MemArg, ValType as V};

pub(super) const META_BASE: i32 = 500_000;
fn mem(offset: u64) -> MemArg {
    MemArg {
        offset,
        align: 2,
        memory_index: 0,
    }
}
fn byte() -> MemArg {
    MemArg {
        offset: 0,
        align: 0,
        memory_index: 0,
    }
}

fn mark(pointer: u32, end: i32) -> Vec<I<'static>> {
    vec![
        I::LocalGet(pointer),
        I::I32Const(HEAP_START),
        I::I32GeU,
        I::LocalGet(pointer),
        I::I32Const(end),
        I::I32LtU,
        I::I32And,
        I::If(B::Empty),
        I::LocalGet(pointer),
        I::I32Const(HEAP_START),
        I::I32Sub,
        I::I32Const(STRIDE),
        I::I32RemU,
        I::I32Eqz,
        I::If(B::Empty),
        I::LocalGet(pointer),
        I::I32Load(mem(4)),
        I::I32Const(1),
        I::I32Eq,
        I::If(B::Empty),
        I::LocalGet(pointer),
        I::I32Const(2),
        I::I32Store(mem(4)),
        I::End,
        I::End,
        I::End,
    ]
}

pub(super) fn collect(slots: i32) -> Function {
    let end = HEAP_START + slots * STRIDE;
    // locals: root offset, child pointer, object pointer, cell index, changed.
    let mut code = vec![
        I::Block(B::Empty),
        I::Loop(B::Empty),
        I::LocalGet(0),
        I::GlobalGet(0),
        I::I32GeU,
        I::BrIf(1),
        I::LocalGet(0),
        I::I32Load(mem(0)),
        I::LocalSet(1),
    ];
    code.extend(mark(1, end));
    code.extend([
        I::LocalGet(0),
        I::I32Const(4),
        I::I32Add,
        I::LocalSet(0),
        I::Br(0),
        I::End,
        I::End,
    ]);
    code.extend([
        I::I32Const(super::host::TABLE),
        I::LocalSet(0),
        I::Block(B::Empty),
        I::Loop(B::Empty),
        I::LocalGet(0),
        I::I32Const(super::host::TABLE + 256 * 16),
        I::I32GeU,
        I::BrIf(1),
        I::LocalGet(0),
        I::I32Load(mem(0)),
        I::LocalSet(1),
    ]);
    code.extend(mark(1, end));
    code.extend([
        I::LocalGet(0),
        I::I32Const(16),
        I::I32Add,
        I::LocalSet(0),
        I::Br(0),
        I::End,
        I::End,
        I::Loop(B::Empty),
        I::I32Const(0),
        I::LocalSet(4),
        I::I32Const(HEAP_START),
        I::LocalSet(2),
        I::Block(B::Empty),
        I::Loop(B::Empty),
        I::LocalGet(2),
        I::I32Const(end),
        I::I32GeU,
        I::BrIf(1),
        I::LocalGet(2),
        I::I32Load(mem(4)),
        I::I32Const(2),
        I::I32Eq,
        I::If(B::Empty),
        I::I32Const(1),
        I::LocalSet(4),
        I::LocalGet(2),
        I::I32Const(3),
        I::I32Store(mem(4)),
        I::I32Const(0),
        I::LocalSet(3),
        I::Block(B::Empty),
        I::Loop(B::Empty),
        I::LocalGet(3),
        I::LocalGet(2),
        I::I32Load(mem(0)),
        I::I32Const(8),
        I::I32DivU,
        I::I32GeU,
        I::BrIf(1),
        I::LocalGet(2),
        I::I32Const(HEAP_START),
        I::I32Sub,
        I::I32Const(STRIDE),
        I::I32DivU,
        I::I32Const(64),
        I::I32Mul,
        I::I32Const(META_BASE),
        I::I32Add,
        I::LocalGet(3),
        I::I32Const(8),
        I::I32DivU,
        I::I32Add,
        I::I32Load8U(byte()),
        I::I32Const(1),
        I::LocalGet(3),
        I::I32Const(8),
        I::I32RemU,
        I::I32Shl,
        I::I32And,
        I::If(B::Empty),
        I::LocalGet(2),
        I::LocalGet(3),
        I::I32Const(8),
        I::I32Mul,
        I::I32Add,
        I::I32Load(mem(8)),
        I::LocalSet(1),
    ]);
    code.extend(mark(1, end));
    code.extend([
        I::End,
        I::LocalGet(3),
        I::I32Const(1),
        I::I32Add,
        I::LocalSet(3),
        I::Br(0),
        I::End,
        I::End,
        I::End,
        I::LocalGet(2),
        I::I32Const(STRIDE),
        I::I32Add,
        I::LocalSet(2),
        I::Br(0),
        I::End,
        I::End,
        I::LocalGet(4),
        I::BrIf(0),
        I::End,
        I::I32Const(HEAP_START),
        I::LocalSet(2),
        I::I32Const(0),
        I::LocalSet(4),
        I::Block(B::Empty),
        I::Loop(B::Empty),
        I::LocalGet(2),
        I::I32Const(end),
        I::I32GeU,
        I::BrIf(1),
        I::LocalGet(2),
        I::I32Load(mem(4)),
        I::I32Const(1),
        I::I32Eq,
        I::If(B::Empty),
        I::LocalGet(2),
        I::I32Const(0),
        I::I32Store(mem(4)),
        I::LocalGet(4),
        I::I32Const(1),
        I::I32Add,
        I::LocalSet(4),
        I::Else,
        I::LocalGet(2),
        I::I32Load(mem(4)),
        I::I32Const(3),
        I::I32Eq,
        I::If(B::Empty),
        I::LocalGet(2),
        I::I32Const(1),
        I::I32Store(mem(4)),
        I::End,
        I::End,
        I::LocalGet(2),
        I::I32Const(STRIDE),
        I::I32Add,
        I::LocalSet(2),
        I::Br(0),
        I::End,
        I::End,
        I::LocalGet(4),
        I::End,
    ]);
    let mut function = Function::new([(5, V::I32)]);
    for instruction in code {
        function.instruction(&instruction);
    }
    function
}
