[package]
name = "morrow-phase-benchmarks"
version = "0.0.0"
edition = "2021"
rust-version = "1.100"
publish = false

[workspace]

[dependencies]
morrow = { path = "../../crates/morrow" }

[dev-dependencies]
criterion = { version = "=0.5.1", default-features = false, features = ["cargo_bench_support"] }

[[bench]]
name = "phases"
harness = false

[profile.dev]
debug = 0
incremental = false

[profile.test]
debug = 0
incremental = false
