[package]
name = "fern-sim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
fern-web-app = { path = "../fern-web-app", features = ["simulation"] }
fern-web-protocol = { path = "../fern-web-protocol" }
fern-runtime = { path = "../fern-runtime", default-features = false, features = ["simulation"] }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
sha2 = "=0.11.0"
libc.workspace = true
