[package]
name = "fern-runtime-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["staticlib"]
test = false
doctest = false

[dependencies]
fern-runtime = { path = "../fern-runtime" }
